# Generated by Django 6.0.1 on 2026-03-05 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_gameprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameProfile',
        ),
    ]
